export const SPORT_CHANGED = 'SPORT_CHANGED';
export const EQUIPE_CHANGED = 'EQUIPE_CHANGED';
export const CLASSEMENT_CHANGED = 'GET_CLASSEMENT';
export const COMPETITION_CHANGED = 'COMPETITION_CHANGED';
export const FAVORI_CHANGED = 'FAVORI_CHANGED';
export const MATCH_CHANGED = 'MATCH_CHANGED';