export const SPORT_CHANGED = 'SPORT_CHANGED';
export const SPORT_LOAD = 'SPORT_LOAD';
export const EQUIPE_LOAD = 'EQUIPE_CHANGED';
export const CLASSEMENT_LOAD = 'GET_CLASSEMENT';
export const COMPETITIONS_LOAD = 'COMPETITION_CHANGED';
export const FAVORI_CHANGED = 'FAVORI_CHANGED';
export const MATCH_CHANGED = 'MATCH_CHANGED';