version: "3"

services:
  node:
    build: .
    ports:
      - "19000:19000"
      - "19006:19006"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - .:/app
    command: ["/bin/sh", "-c", "npm install --save-dev @types/react-native && npm install && expo start --web"]